version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpw
      DB_NAME: zeneiskola_mysql
      DB_PORT: 3306
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: zeneiskola_db
    command: 
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_hungarian_ci"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: zeneiskola_mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpw
      UPLOAD_LIMIT: 64M

volumes:
  mysql_data: